import type { PermissionAction, UserRole } from "@/data/types";

export const PERMISSION_MODULES = [
  "Marketplace",
  "RFQ Center",
  "Offers",
  "Orders",
  "Finance",
  "Data Room",
  "Service Network",
  "Network Map",
  "Admin",
  "Users & Roles",
  "Sales Partners",
  "Supplier Onboarding",
] as const;

const FULL: PermissionAction[] = ["view", "create", "edit", "approve", "export", "admin"];

export const ROLE_PERMISSIONS: Record<
  UserRole,
  Record<(typeof PERMISSION_MODULES)[number], PermissionAction[]>
> = {
  admin: Object.fromEntries(PERMISSION_MODULES.map((m) => [m, FULL])) as Record<
    (typeof PERMISSION_MODULES)[number],
    PermissionAction[]
  >,
  customer: {
    Marketplace: ["view", "create"],
    "RFQ Center": ["view", "create", "edit"],
    Offers: ["view", "create"],
    Orders: ["view", "export"],
    Finance: ["view", "create"],
    "Data Room": ["view", "create", "edit"],
    "Service Network": ["view", "create"],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  supplier: {
    Marketplace: ["view", "create", "edit"],
    "RFQ Center": ["view", "create", "edit"],
    Offers: ["view", "create", "edit"],
    Orders: ["view"],
    Finance: ["view"],
    "Data Room": ["view", "create", "edit"],
    "Service Network": ["view"],
    "Network Map": [],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  dealer: {
    Marketplace: ["view", "create"],
    "RFQ Center": ["view", "create"],
    Offers: ["view", "create", "edit"],
    Orders: ["view", "create"],
    Finance: ["view", "create"],
    "Data Room": ["view"],
    "Service Network": ["view", "create"],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  sales_partner: {
    Marketplace: ["view", "create"],
    "RFQ Center": ["view", "create", "edit"],
    Offers: ["view", "create", "edit"],
    Orders: ["view"],
    Finance: ["view", "create"],
    "Data Room": ["view", "create"],
    "Service Network": ["view"],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": ["view", "create", "edit"],
    "Supplier Onboarding": [],
  },
  service_partner: {
    Marketplace: ["view"],
    "RFQ Center": ["view"],
    Offers: [],
    Orders: ["view", "edit"],
    Finance: [],
    "Data Room": ["view"],
    "Service Network": ["view", "create", "edit", "approve"],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  finance_partner: {
    Marketplace: ["view"],
    "RFQ Center": ["view"],
    Offers: ["view", "create", "edit", "approve"],
    Orders: ["view"],
    Finance: ["view", "create", "edit", "approve", "export"],
    "Data Room": ["view", "edit", "approve"],
    "Service Network": [],
    "Network Map": [],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  agency: {
    Marketplace: ["view"],
    "RFQ Center": ["view"],
    Offers: [],
    Orders: [],
    Finance: [],
    "Data Room": [],
    "Service Network": [],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
  logistics: {
    Marketplace: ["view"],
    "RFQ Center": [],
    Offers: [],
    Orders: ["view", "edit", "approve"],
    Finance: [],
    "Data Room": [],
    "Service Network": [],
    "Network Map": ["view"],
    Admin: [],
    "Users & Roles": [],
    "Sales Partners": [],
    "Supplier Onboarding": [],
  },
};

export function hasPermission(
  role: UserRole,
  module: (typeof PERMISSION_MODULES)[number],
  action: PermissionAction
): boolean {
  return ROLE_PERMISSIONS[role][module]?.includes(action) ?? false;
}
